CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    firstName TEXT NULL,
    lastName TEXT NULL,
    fullName TEXT NOT NULL,
    email TEXT NULL,
    mesa INTEGER DEFAULT 0,
    register INTEGER DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);